**Step 1: Importing all necessary libraries for EDA**

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
#reading the dataset

clv_df = pd.read_csv(r"C:\Users\Collins Njagi\Documents\Data_Science_tech_class\clv-regression-retail-finserv\clv_dataset.csv")

clv_df.head()

,customer_id,age,gender,region,customer_segment,tenure_months,avg_monthly_spend,avg_transaction_value,purchase_frequency,num_products_owned,engagement_score,churn_risk_score,satisfaction_score,email_open_rate,days_since_last_purchase,num_support_calls,discount_usage_rate,preferred_channel,payment_method,customer_lifetime_value
0,C000001,NaN,Male,NaN,Basic,41.782826,478.147262,104.480104,15.500257,3,86.424825,23.611367,2.0,52.944471,NaN,1.0,36.518708,NaN,NaN,32723.792179
1,C000002,59.960182,Male,NaN,Standard,24.676991,414.103659,144.542648,19.131489,4,85.995060,22.559350,5.0,42.959542,NaN,2.0,43.100198,In-Store,Credit Card,32500.409711
2,C000003,49.244677,Female,South,Standard,24.751584,395.523475,143.348133,12.786573,3,58.085044,66.092561,4.0,NaN,NaN,2.0,35.311116,Online,NaN,26755.704064
3,C000004,22.405579,Female,West,Basic,14.250395,1208.645086,156.953659,3.647866,1,77.046072,13.792950,4.0,72.653849,NaN,4.0,73.751273,Online,PayPal,32419.715565
4,C000005,36.320996,Female,NaN,Standard,27.340128,499.168096,44.189692,10.229082,4,67.583741,17.963247,NaN,NaN,NaN,2.0,29.391164,In-Store,Credit Card,29137.203584

In [5]:
clv_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               15000 non-null  str
 1   age                       12500 non-null  float64
 2   gender                    15000 non-null  str
 3   region                    9000 non-null   str
 4   customer_segment          15000 non-null  str
 5   tenure_months             15000 non-null  float64
 6   avg_monthly_spend         15000 non-null  float64
 7   avg_transaction_value     12500 non-null  float64
 8   purchase_frequency        15000 non-null  float64
 9   num_products_owned        15000 non-null  int64
 10  engagement_score          15000 non-null  float64
 11  churn_risk_score          12500 non-null  float64
 12  satisfaction_score        12500 non-null  float64
 13  email_open_rate           12500 non-null  float64
 14  days_since_last_purchase  9000 non-null   float64
 15  num_support_calls         12500 non-null  float64
 16  discount_usage_rate       9000 non-null   float64
 17  preferred_channel         9000 non-null   str
 18  payment_method            9000 non-null   str
 19  customer_lifetime_value   15000 non-null  float64
dtypes: float64(13), int64(1), str(6)
memory usage: 2.3 MB

In [6]:
clv_df.describe()

,age,tenure_months,avg_monthly_spend,avg_transaction_value,purchase_frequency,num_products_owned,engagement_score,churn_risk_score,satisfaction_score,email_open_rate,days_since_last_purchase,num_support_calls,discount_usage_rate,customer_lifetime_value
count,12500.000000,15000.000000,15000.000000,12500.000000,15000.000000,15000.000000,15000.000000,12500.000000,12500.000000,12500.000000,9000.000000,12500.00000,9000.000000,15000.000000
mean,45.324942,23.983111,498.862721,149.401165,11.989860,3.068800,71.389229,28.544770,3.746000,59.682694,29.771525,1.98128,40.103912,30041.895299
std,14.384654,13.890450,222.745751,85.055486,8.416213,1.689494,15.956685,15.966427,1.133202,20.104804,29.912252,1.40700,19.892577,6584.092957
min,18.000000,1.000000,39.185138,5.000000,1.000000,1.000000,7.438690,0.109897,1.000000,2.290868,0.011121,0.00000,0.445363,14053.148523
25%,34.952307,13.797306,334.889185,87.067546,5.748429,2.000000,60.977005,16.110962,3.000000,45.196314,8.509332,1.00000,24.674302,25951.380964
50%,45.259362,21.264697,465.923007,133.510606,10.085723,3.000000,73.572208,26.438257,4.000000,60.875394,20.414921,2.00000,38.703184,29029.280431
75%,55.209986,31.384745,627.732330,194.236809,16.115042,4.000000,83.819742,38.947638,5.000000,75.518379,40.885270,3.00000,54.303423,32538.972115
max,80.000000,120.000000,1729.118237,655.943759,71.433420,14.000000,99.636592,93.324691,5.000000,99.649630,330.389154,9.00000,97.486913,75614.325780

**Checking for  Duplicates**

In [9]:
clv_df.duplicated().sum()

np.int64(0)

In [15]:
#clv_df['region'].unique()
#clv_df['customer_segment'].unique()
#clv_df['preferred_channel'].unique()
#clv_df['payment_method'].unique()

cat_cols = clv_df.select_dtypes(include = 'object')

C:\Users\Collins Njagi\AppData\Local\Temp\ipykernel_20368\846144353.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  clv_df.select_dtypes(include = 'object')

,customer_id,gender,region,customer_segment,preferred_channel,payment_method
0,C000001,Male,NaN,Basic,NaN,NaN
1,C000002,Male,NaN,Standard,In-Store,Credit Card
2,C000003,Female,South,Standard,Online,NaN
3,C000004,Female,West,Basic,Online,PayPal
4,C000005,Female,NaN,Standard,In-Store,Credit Card
...,...,...,...,...,...,...
14995,C014996,Female,NaN,Basic,NaN,NaN
14996,C014997,Female,NaN,Standard,NaN,Debit Card
14997,C014998,Male,South,Basic,NaN,NaN
14998,C014999,Female,NaN,Standard,In-Store,Debit Card
14999,C015000,Male,West,Premium,NaN,NaN

In [ ]:
# Preferred: get column NAMES (Index) rather than the whole dataframe
cat_cols = clv_df.select_dtypes(include='object').columns
# show the categorical columns
print('Categorical columns:', list(cat_cols))

# Loop: print number of unique values and top frequencies for each categorical column
for col in cat_cols:
    print(f"\nColumn: {col} — {clv_df[col].nunique()} unique values")
    print(clv_df[col].value_counts(dropna=False).head(10))